Update act1.md
tezzutezzu/anxiety pull request #13
Opened 2021-01-31 19:32 UTC by Cacho-tognax

Cleaned up some translations, added context for a pun, marked an unmarked swear word.

2021-01-31 20:53 UTC, tezzutezzu commented on scenes/act1.md
> +b: Sciupando quindi la trama di questo universo narrativo,
Sciupando è la traduzione corretta

2021-01-31 20:56 UTC, tezzutezzu requested changes

2021-01-31 20:56 UTC, tezzutezzu commented on scenes/act1.md
> +n: HAI USATO LA *PAURA DI FARSI MALE*
questo dovrebbe essere cambiato in tutte le altre scene

2021-01-31 22:06 UTC, Cacho-tognax commented on scenes/act1.md
> +b: Sciupando quindi la trama di questo universo narrativo,
Volevo addirittura usare "disfacendo" ma è bruttina forse, "disfando" è scorretto, e non ho trovato meglio.
Comunque "sbrogliando" non mi piaceva per niente, non c'era niente di imbrogliato.

2021-02-01 10:13 UTC, tezzutezzu commented on scenes/act1.md
> +n: HAI USATO LA *PAURA DI FARSI MALE*
"Farsi male" mi sembra più adatto allo stile narrativo, apro una PR per cambiare tutti gli altri,.

2021-02-01 10:13 UTC, tezzutezzu commented on scenes/act1.md
> +b: Sciupando quindi la trama di questo universo narrativo,
Ok

2021-02-01 10:14 UTC, merged

2021-02-01 10:21 UTC, tezzutezzu commented on scenes/act1.md
> +n: HAI USATO LA *PAURA DI FARSI MALE*
Fatto un commit per le altre scene